lines_per_method: 6
line_length: 90
max_nesting_depth: 2
methods_per_class: 12
no_semicolons: true
no_trailing_whitespace: true
check_syntax: true
no_global_variables: true
english_words_for_names: 'rasterize rasterization renderer renderers html ascii eql bresenham vertices'
naming_conventions: true
